### ISSUE TITLE
Mass-Drawing-Edits with Advanced-Drawing-Tools enabled fail when"0"-values are used.

### ISSUE THREAD

**Issue by kagedansa** [Aedif/multi-token-edit#7]
With "Mass-Drawing-Edit" it is not possible to set values with "0" in combination with the Advanced-Drawing-Tools-module. If you use a value with "0" in the texture-size-, texture-pivot- or texture-position-fields nothing happens. Values greater than "0" work without any problem.

**Comment by Aedif** [comment]
It wasn't working for me with any values. I made an adjustment though and it should be working now as of release [1.12.1](https://github.com/Aedif/multi-token-edit/releases/tag/1.12.1)

**Comment by kagedansa** [comment]
Unfortunately, this did not solve the problem for me.
I can change values from 0 to anything greater than 0, but not back again.
However, no error message appears in the console.
It seems to be triggered somehow by lib-wrapper. If I deactivate this module alone the issue ist not present.
Leider ist es, neben den Advanced-Drawing-Tools,  eine Voraussetzung für viele module.

**Comment by Aedif** [comment]
Hmm,. it works for me with both llibWrapper on and off, on version v10 and v9 of Foundry. I think there is a conflict with some other 3rd module that you might have installed that is using libWrapper..

**Comment by kagedansa** [comment]
For testing, I had only the modules Advanced Drawing Tools, Mass Edit and lib-wrapper active.
Foundry version is 10.285

**Comment by kagedansa** [comment]
There is always only one message in the console-log. But it is always there no matter if editing without lib-wrapper works or with lib-wrapper doesn't work.
![log](https://user-images.githubusercontent.com/110729103/190362538-85f38b7f-1c97-48be-99fb-0b34d0ea0cda.png)

The color used is: #ffffff

**Comment by kagedansa** [comment]
I tested some more. The problem occurs in V9 as well as in V10 and editing with lib-wrapper active always fails when you try to reset to the original default values.
This is the "0" at position, pivot, rotation and skew, but also the "1" at scale or "auto" at size.

**Comment by Aedif** [comment]
What game system are you testing this on?

**Comment by kagedansa** [comment]
Hexxen 1733 and Conan on V10
Coriolis and Hexxen 1733 on V9

**Comment by Aedif** [comment]
Alright was able to reproduce, I'll add a fix for it in the next release.

**Comment by Aedif** [comment]
Should be fixed in release [1.12.2](https://github.com/Aedif/multi-token-edit/releases/tag/1.12.2)

**Comment by kagedansa** [comment]
Works with V9 and V10 now! Thanks alot!
